server:
  port: 8081
  #context
  context-path: /tmall_springboot #无效
  servlet:
    context-path: /tmall_springboot

#database
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/my_tmall_springboot?characterEncoding=utf8&serverTimezone=GMT
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

#thymeleaf
  thymeleaf:
    mode: LEGACYHTML
    encoding: utf-8
    content-type: text/html
    cache: false

#设置上传文件大小，默认只有1 m
  http:
    multipart:
      max-file-size: 100Mb
      max-request-size: 100Mb

  data:
    elasticsearch:
      cluster-nodes: 127.0.0.1:9300
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    password:
